[package]
name = "node_compiler"
version = "0.1.0"
edition = "2024"

[features]
default = ["human-readable"]
human-readable = ["dep:ron"]

[dependencies]
ron = { version = "0.8", optional = true }
eframe = { version = "0.33", features = ["persistence"] }
egui = "0.33"
egui-snarl = { version = "0.9.0", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
postcard = { version = "1", features = ["alloc"] }
rfd = "0.15"
log = { version = "0.4", features = ["release_max_level_off"] }
env_logger = "0.11"
sha3 = "0.10"
anyhow = "*"
